# -*- coding: utf-8 -*-
"""EXERCICIOS Fluxo Algorítmico.ipynb - ABNER CARDOZO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXhJFPdiRqT3TQiPs2rL_-crsfHwI1wu

<html>
  <body>
    <header></header>
        <CENTER>
          <img src="https://docentes.uvv.br/Content/img/logo-uvv.png" alt="UVV-LOGO" style = width="100px"; height="100px">
        </CENTER>
        <CENTER>
          <b>
            <font size="5">Laboratório de Programação
          </b>
          </CENTER>
        <CENTER><b>DICA: Metodologia de Estudo</b></CENTER><br/>
        </font>

**NOME:**

CRIAR / COMPARTILHAR AQUI UM LINK PARA SEU PRÓPRIO NOTEBOOK COLAB: [Clique Aqui!]()

# LETRA A
a) Calcular e exibir a hipotenusa (A) de um triângulo retângulo de catetos B e C, sabendo que:

A = √B2 + C
"""

# ALGORITMO: ENTRADA (Usuário) + PROCESSAMENTO (ULA) + SAÍDA (Objetivo)
try:

  import math
  #ENTRADA(INPUT)
  variavelB = float(input('Insira o valor de B:'))
  variavelC = float(input('Insira o valor de C'))

  #PROCESSAMENTO
  valorA = variavelB**2 + variavelC

  #SAÍDA(PRINT)
  print('O valor da hipotenusa é: {isqrt(n)valorA}')

except(ValueError):
  print('Valor inválido')


# NÃO APAGAR SUA TENTATIVA, MESMO QUE INCORRETA !!!

try:
  import math #IMPORTAÇÃO
  #ENTRADA(INPUT)
  variavelB=float(input('Insira o valor de B:'))
  variavelC = float(input('Insira o valor de C:'))

  #PROCESSAMENTO
  hipotenusa = math.sqrt(variavelB**2 + variavelC**2)

  #SAÍDA(PRINT)
  print(f'O valor da hipontenusa é: {hipotenusa:.2f}')

except(ValueError):
    print('Valor inválido')

"""# LETRA B

b) Calcular e exibir a área de um quadrado de lado (L). Área = L2





"""

try:
  #ENTRADA(INPUT)
  valorL = float(input('Insira o valor de L:'))

  #PROCESSAMENTO
  area = valorL**2

  #SAÍDA(PRINT)
  print(f'O valor da área é: {area:.2f}')

except(ValueError):
  print('Valor inválido')

"""# LETRA C
c) Calcular e exibir a área de um retângulo de lado (L) e altura (H). Área = L * H.

```
# Isto está formatado como código
```


"""

try:
  #ENTRADA(INPUT)
  lado = float(input('Insira o valor de L:'))
  altura = float(input('Insira o valor de H:'))

  #PROCESSAMENTO
  area = lado * altura

  #SAÍDA(PRINT)
  print(f'O valor da área é: {area:.2f}')

except(ValueError):
  print('Valor inválido')

"""#LETRA D:
Calcular e exibir a área e o comprimento de um círculo de Raio (R), sabendo que, Área = π * R2
e

Comprimento = 2 * π * R.
"""

try:
  #ENTRADA(INPUT)
  #IMMPORTAÇÃO
  import math

  raio = float(input('Insira o valor do raio:'))

  #PROCESSAMENTO
  area = math.pi * (raio**2)
  comprimento = 2 * math.pi * raio

  #SAÍDA(PRINT)
  print(f'O valor da área é: {area:.2f}')
  print(f'O valor do comprimento é: {comprimento:.2f}')

except(ValueError):
  print('Valor inválido')

"""#LETRA E
Calcular e exibir o IMC (Índice de Massa Corpórea) de uma pessoa de altura (H) em metros e massa
(M) em quilogramas, sabendo que IMC = M / H2
"""

try:
  #ENTRADA(INPUT)
  altura = float(input('Insira o valor da altur
  a:'))
  massa = float(input('Insira o valor da massa:'))

  #PROCESSAMENTO
  imc = massa / altura**2

  #SAÍDA(PRINT)
  print(f'O valor do IMC é: {imc:.2f}')

except(ValueError):
  print('Valor inválido')

"""#LETRA F:

Calcular e exibir o volume em litros de uma esfera de Raio (R), sabendo que o usuário deve informar
o Raio (R) em metros. Sabe-se que: VolumeEsfera = 4
3
⁄ * π * R3

e que 1 Litro é igual a 10-3 m3
"""

try:
  #ENTRADA(INPUT)
  import math
  raio = float(input('Informa o valor do raio em metros:'))

  #PROCESSAMENTO

  volumeEsfera = 4/3 * math.pi * raio**3 * 10**-3

  #SAÍDA (PRINT)
  print(f'O valor do volume da esfera é: {volumeEsfera:.2f}')

except(ValueError):
  print('Valor inváliddo')

"""#LETRA G
Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no
mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11%
para o Imposto de Renda, 8% para o INSS e 5% para o sindicato. Com isso, exiba na tela:


*   salário bruto.
*   quanto pagou ao INSS.
*  quanto pagou ao sindicato.
*  o salário líquido = Brutos - Descontos.
"""

try:
  #ENTRADA(INPUT)
  horasMes = float(input('Informa quantas horas você trabalha no mês:'))
  valorHora = float(input('Informa o quanto você ganha por hora:'))

  #PROCESSAMENTO
  salarioBruto = horasMes * valorHora
  impostoRenda = salarioBruto * 0.11
  inss = salarioBruto * 0.08
  sindicato = salarioBruto * 0.05
  salarioLiquido = salarioBruto - impostoRenda - inss - sindicato

  #SAÍDA(PRINT)
  print(f'O valor do salário bruto é: {salarioBruto:.2f}')
  print(f'O valor pago ao INSS é: {inss:.2f}')
  print(f'O valor pago ao sindicato é: {sindicato:.2f}')
  print(f'O valor do salário líquido é: {salarioLiquido:.2f}')

except(ValueError):
  print('Valor inválido')

"""#LETRA  H
Calcular e exibir a quantidade de tinta (em latas) e o custo (em reais) para pintar um tanque cilíndrico
de base circular de Raio (R) e altura (H) em metros, sabendo que:

*   1 lata = 5 litros.
*   1 litro pinta 3 metros quadrados.
*   1 lata custa 50 Reais.
"""

try:
  #ENTRADA(INPUT)
  lata = float(input('Informa a quantidade de latas:'))

  #PROCESSAMENTO
  lataLitro = 5
  area = lata * latalitro * 3
  custo = area * 50

  #SAÍDA(PRINT)
  print(f'A quantidade de latas é: {lata:.2f}')
  print(f'O custo é: {custo:.2f}')

except(ValueError):
  print('Valor inválido

"""#LETRA I
Calcular e exibir a distância entre dois pontos quaisquer do plano, P(x1, y1) e Q(x2, y2), sabendo que
a fórmula da distância é d = √(x2 – x1)

2 + (y2 – y1)

2, sendo os pontos P(x1, y1) e Q(x2, y2) como

dados de entrada.
"""

try:
  #ENTRADA(INPUT)
  #IMPORTAÇÃO
  import math

  x1 = float(input('Informe o valor de x1:'))
  x2 = float(input('Informe o valor de x2:'))
  y1 = float(input('Informe o valor de y1:'))
  y2 = float(input('Informe o valor de y2:'))

  #PROCESSAMENTO
  distancia = math.sqrt((x2 - x1)**2 + (y2 - y1)** 2)

  #SAÍDA(PRINT)
  print(f'A distância entre os pontos é de: {distancia:.2f}')

except(ValueError):
  print('Valor inválido')

"""#LETRA J
Calcular e exibir o tempo (em horas) de autonomia de uma caixa d’água de um restaurante que
consome 1350 litros por hora em média. O tanque do restaurante é cilíndrico de base circular de Raio
(R) e de altura (H) em metros. Sabendo que 1 m3 = 1000 Litros.
"""

try:
  #ENTRADA (INPUT)
  import math

  raio = float(input('Informe o valor do raio:'))
  altura = float(input('Informe o valor da altura:'))

  #PROCESSAMENTO
  volume = math.pi * raio**2 * altura
  litros = volume * 1000
  tempo = litros / 1350

  #SAÍDA(PRINT)
  print(f'O tempo de autonomia é de: {tempo:.2f} horas')

except(ValueError):
  print('Valor inválido')

"""#LETRA K
Faça um programa que peça o tamanho de um arquivo para download (em Megabytes) e a
velocidade de um link de Internet (em Megabytes / Segundo), calcule e informe o tempo: Minutos +
Segundos aproximado de download do arquivo usando este link.
"""

try:
  #ENTRADA(INPUT)
  tamanhoArquivo = float(input('Informe o tamanho do arquivo em MegaByte:'))
  velocidadeInternet = float(input('Informe a velocidade da internet em Megabyte/Segundo:'))

  #PROCESSAMENTO
  tempo =  tamanhoArquivo / velocidadeInternet
  minutos = tempo // 60
  segundos = tempo % 60

  #SAÍDA(PRINT)
  print(f'O tempo de download é de: {tempo:.2f} minutos {minutos:.2f} e segundos {segundos:.2f}')

except(ValueError):
  print('Valor inválido')

"""#LETRA L
Calcular e exibir a distância máxima (em Quilômetros) de autonomia de um carro que possui um
tanque de combustível cúbico de lado (L) em metros e Altura (h) de preenchimento do tanque.
Sabendo que seu consumo é em média 10 km/litro. Sabendo que 1 m3 = 1000 Litros.
"""

try:
  #ENTRADA(INPUT)
  import math

  lado = float(input('Informe o valor do lado:'))
  altura = float(input('Informe o valor da altura:'))

  #PROCESSAMENTO
  volume = math.pi * lado**2 * altura
  litros = volume * 1000
  mediaKm = litros / 10
  distancia = mediaKm * 1000

  #SAÍDA(PRINT)
  print(f'A distância máxima é de: {distancia:.2f} km')

except(ValueError):
  print('Valor inválido')

"""#OBRIGATÓRIO: CONVERTER IPYNB para PDF:

**PASSO A PASSO:**

1.   Fazer o download do seu IPYNB.
2.   Fazer o upload do seu IPYNB para área temporária: content.
3.   Rodar o código abaixo com output.ipynb: Gerar um HTML.
4.   Fazer o download do seu HTML e abrir em um Browser qualquer.
3.   Imprimir a página HTML em PDF. Pronto (UFA)::: 😅!

**MOTIVO:** Seus Gráficos, Códigos Python e Células **NÃO** sairão **" CORTADOS "** de uma página para outra.
"""

# Commented out IPython magic to ensure Python compatibility.
# # .../content/output.ipynb: é o PATH temporário do COLAB: Upload para a pasta ARQUIVOS, ao lado
# %%shell
# jupyter nbconvert --to html /content/output.ipynb